[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
auto_detect_solc = true
optimizer = true
optimizer_runs = 200

[etherscan]
base = { key = "CKCSUNW8CXHQ1FZVGAN2XR7HEUSGFCIBK5", chain = 8453, url = "https://basescan.org/" }