[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.24"  # Versión principal que usas
auto_detect_solc = true
allowed_solc_versions = ["0.8.24", "0.7.6"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
